export const WAREHOUSE_NAME = process.env.NEXT_PUBLIC_WAREHOUSE_NAME || "Your Warehouse";
export const WAREHOUSE_LOGO_URL = process.env.NEXT_PUBLIC_WAREHOUSE_LOGO_URL || null;
export const WAREHOUSE_ACCENT_COLOR = process.env.NEXT_PUBLIC_WAREHOUSE_ACCENT_COLOR || "#8a3a2e";
export const WAREHOUSE_SECONDARY_COLOR = process.env.NEXT_PUBLIC_WAREHOUSE_SECONDARY_COLOR || "#1D4ED8";
export const WAREHOUSE_CONTACT_PHONE = process.env.NEXT_PUBLIC_WAREHOUSE_CONTACT_PHONE || null;
